language: go
go:
- '1.12'
script:
- go test ./...
- |
  if [[ "${TRAVIS_TAG}" ]]; then
      .travis/build.sh
  fi
deploy:
  provider: releases
  api_key:
    secure: Yz768vOOE+wRV6ilUB6ukAO/GjSbkQ4YruhLWCN5CoZn81c9YW04HaTXOvQIhqbZRN7Dfvx9EbtLhqlaHq5qnmzipFN3gCKNhD6oUCwE03lm69QDFI3TdrMkOFfUoZBbmNPI4+W7nqmmWVDfX0hyqw5qHnm38ZBJ65QlSrbeJ6acKrZ6VPQ6LelEEI3ItdpaDSy7XaO/HvPcXx8jQEQKIJJvXruGgfZghZ1NzHPYrcBwL4qa26A7b4s/ngDxhal0rX91/auqRi6nphkKN9Fn9YhG4tCdp0W3qdgyA2BtQuWCRsfoZHw3PCbUkrT4H70wfB2Fu4Ih4eN2hdKdc/AessqXpphoSD35BdH+TVJ8mw72To98Al6hqkkaaH0t31A21OEFY0ZMvpbekGZkbDOCItA7pTxKXeuD74binWUS0m5OWsYdpCp2NIpcBeJHxLXv9Xn+9v5Aaft3MQ1/TpulMys9spNhkpmeEncHW3Ego9fVyTi+L1IfH/E9dwcdRBzbixeq/963bxUiSCjUr7lpTZsnEmbTn6inrDDLC4ZgJTXZ2jm0zErIS2Q+g600GiaWcuFcZN6zdXxOSZSXunRDybHH6QyQU1K57GnTtYQ6arvuyOVxBDaOPmbDiVphhjapbTq/IaaicEQMT0hA2hbUiYk57iqyh7Prtsz4KNOFw0w=
  file: target/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: jwilner/envly
